### ISSUE TITLE
listing page

### ISSUE THREAD

**Issue by balibpt** [wenghaishi/1160-airbnb-clone#13]
Dependent on database migration and seeding of data.

- [ ] Ensure that the main card is created and implemented.
- [ ] Ensure that the font, CSS, color and size follows the original AirBnb website.
- [ ] Ensure clean and dry code.

**Comment by ernest-heh** [comment]
![Image](https://user-images.githubusercontent.com/105141510/224888775-688b7f61-8c6b-4fb1-a87b-000025567fa1.jpg)

- [ ] Style show.html.erb for individual listing
