### ISSUE TITLE
As a user I can view all listings. Basic template for airbnb

### ISSUE THREAD

**Issue by balibpt** [wenghaishi/1160-airbnb-clone#25]
- [ ] Create a basic frontend home page with seeded data from db. Dependent on Db migrations and seeding. 

- [ ] Generate listings_controller with #index

- [ ] Ensure the creation of the card component

**Comment by ernest-heh** [comment]
![Image](https://user-images.githubusercontent.com/105141510/224889012-87f0dc3e-54af-45e0-ad1a-a4ce610a5042.jpg)

- [ ] Style individual card for a listing
- [ ] Display cards in a grid layout on index page
