### ISSUE TITLE
As a user, i can delete a listing

### ISSUE THREAD

**Issue by ernest-heh** [wenghaishi/1160-airbnb-clone#49]
Implement feature to authenticate user as the correct host to a listing. (devise)

When the listing belongs to the user, show a delete button. If not, hide the delete button.

Devise can authenticate user to edit the listing as well.

**Comment by wenghaishi** [comment]
![Image](https://user-images.githubusercontent.com/74546450/225201464-7a22c536-631f-433b-83c4-c7ad69131d47.png)
